### ISSUE TITLE
Truncated version in octo-board 

### ISSUE THREAD

**Issue by papapillon** [Zorin95670/octo#3]
Hello,
The displayed version is sometimes truncated in the board.
eg: That displayed  '12.0...' instead of '12.00.0'.

![image](https://user-images.githubusercontent.com/32190153/127191727-272442c8-95f3-4507-a5b4-a72b8197604b.png)

Is it a bug ?
best regard
Fabien

configuration :
Firefox : 90.0 (64-bit)
Octo board : v2.0.2
Octo spy : 1.7.1 
screen : 1920 X 1080

**Comment by Zorin95670** [comment]
Hi, I confirm this is a bug.

Thank's for your report. 

I will notify you when new version will fix it :slightly_smiling_face:.

**Comment by Zorin95670** [comment]
It will fix on `octo-board@2.1.0`, next octo version will include this fix :)

**Comment by Zorin95670** [comment]
Next version (1.1.0) is released :)
