### ISSUE TITLE
The order in which customers are displayed is different depending on the project. 

### ISSUE THREAD

**Issue by papapillon** [Zorin95670/octo#8]
**Describe the bug**
The order in which customers are displayed is different depending on the project. 

**To Reproduce**
1. have several environments
2. have several clients
3. have several deployments for different clients
4. See the dasboard

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/32190153/132354966-494977ee-a149-4a5f-be4b-405682684110.png)

**Application (please complete the following information):**

- Octo board v2.5.0 
- Octo spy 1.11.0

**Comment by Zorin95670** [comment]
Octo version 1.3.0 was release and fix this issue.
